version: 0.2

env:
  variables:
    ECR_REPO: <your-account-id>.dkr.ecr.<region>.amazonaws.com/my-app
    AWS_REGION: <your-region>

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO)

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t my-app .
      - docker tag my-app:latest $ECR_REPO:latest

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $ECR_REPO:latest
      - echo Writing image details to imageDetail.json
      - echo "{\"repository\":\"$ECR_REPO\",\"tag\":\"latest\"}" > imageDetail.json

artifacts:
  files:
    - imageDetail.json
